name: flight_planner
channels:
  - defaults
  - conda-forge
dependencies:
  - bzip2
  - ca-certificates
  - libffi
  - openssl
  - pip
  - python=3.10.9
  - setuptools
  - sqlite
  - tk
  - tzdata
  - wheel
  - xz
  - zlib
  - pip:
      - blinker
      - cachelib
      - certifi
      - click
      - colorama
      - dash
      - dash-bootstrap-components
      - dash-core-components
      - dash-extensions
      - dash-html-components
      - dash-leaflet
      - dash-table
      - editorconfig
      - flask
      - flask-caching
      - geobuf
      - itsdangerous
      - jinja2
      - jsbeautifier
      - markupsafe
      - more-itertools
      - numpy
      - packaging
      - plotly
      - protobuf
      - pyproj
      - shapely
      - six
      - tenacity
      - werkzeug
